title: Daily AWS
paginate: 5
theme: PaperMod

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  ShowShareButtons: false
  ShowToc: true
  ShowPostNavLinks: true

menu:
  main:
  - name: Tags
    url: /tags/
    weight: 10

hasCJKLanguage: true
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  ja:
    languageName: 日本語
    weight: 2

enableRobotsTXT: true
