title: Builder News
paginate: 5
theme: PaperMod

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  #ShowShareButtons: true
  ShowToc: true
  ShowPostNavLinks: true
  comments: true

hasCJKLanguage: true
defaultContentLanguage: ja
languages:
  en:
    languageName: English
    weight: 2
  ja:
    languageName: 日本語
    weight: 1
