title: Builder News
paginate: 5
theme: PaperMod

hasCJKLanguage: true

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  ja:
    languageName: 日本語
    weight: 2

params:
  comments: true
