baseURL: https://news.wktk.dev/
title: Builder News
theme: PaperMod

hasCJKLanguage: true

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 2
  ja:
    languageName: Japanese
    weight: 1
