title: Builder News
paginate: 5
theme: PaperMod

hasCJKLanguage: true

defaultContentLanguage: ja
languages:
  en:
    languageName: English
    weight: 2
  ja:
    languageName: 日本語
    weight: 1

params:
  comments: true
